### ISSUE TITLE
think about using jenkins instead of heroku for this

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-fastly-to-graphite#1]
since it's just a bit of script that needs to run with some api keys.

it's surprising competent at this job: http://ftjen06392-lvpr-uk-p.osb.ft.com:8181/job/heroku-deploy-counter/

**Comment by JakeChampion** [comment]
Could this be done by AWS Lambda instead?

**Comment by matthew-andrews** [comment]
ah this got migrated to a heroku scheduled task. i think it's ok now.
